import fs from 'node:fs';
import path from 'node:path';

/** Site-root path with `.webp` when a matching `.png` exists under `/images/`. */
export function preferWebp(path: string): string {
  if (path.endsWith('.png')) return path.replace(/\.png$/, '.webp');
  return path;
}

const publicDir = path.join(process.cwd(), 'public');

function publicFileExists(siteRootPath: string): boolean {
  const rel = siteRootPath.startsWith('/') ? siteRootPath.slice(1) : siteRootPath;
  return fs.existsSync(path.join(publicDir, rel));
}

/** CSS `background-image` value; uses WebP in `image-set` only when that file exists under `public/`. */
export function cssBackgroundImage(path: string): string {
  const normalized = path.startsWith('/') ? path : `/${path}`;
  if (!normalized.endsWith('.png')) {
    return `url('${normalized}')`;
  }
  const webp = preferWebp(normalized);
  if (publicFileExists(webp)) {
    return `image-set(url('${webp}') type('image/webp'), url('${normalized}') type('image/png'))`;
  }
  return `url('${normalized}')`;
}

export const GALLERY_SRC_WIDTHS = [520, 768, 1040] as const;
export const HERO_POSTER_WIDTHS = [640, 1280, 1920] as const;

const GALLERY_ASPECT = 768 / 1376;

/** Width/height for a gallery tile at a given intrinsic width. */
export function galleryDimensions(width: number): { width: number; height: number } {
  return { width, height: Math.round(width * GALLERY_ASPECT) };
}

function responsiveStem(webpPath: string): string {
  return webpPath.replace(/\.webp$/, '');
}

/** `srcset` for `-{w}w.webp` variants generated by `scripts/optimize-images.mjs`. */
export function responsiveWebpSrcset(
  path: string,
  widths: readonly number[],
): string {
  const webp = preferWebp(path);
  const stem = responsiveStem(webp);
  return widths.map((w) => `${stem}-${w}w.webp ${w}w`).join(', ');
}

/** Default `src` — largest variant in the set (not the legacy full-size master). */
export function responsiveWebpSrc(
  path: string,
  widths: readonly number[],
): string {
  const max = Math.max(...widths);
  return `${responsiveStem(preferWebp(path))}-${max}w.webp`;
}

/** Single variant path, e.g. hero video `poster` at 1280px. */
export function responsiveWebpAt(path: string, width: number): string {
  return `${responsiveStem(preferWebp(path))}-${width}w.webp`;
}

/** Preload `imagesrcset` string for hero poster. */
export function heroPosterPreloadSrcset(): string {
  return responsiveWebpSrcset('/images/hero-poster.webp', HERO_POSTER_WIDTHS);
}
